### ISSUE TITLE
老哥，能不能换一个更好的ui？

### ISSUE THREAD

**Issue by Tongnier** [14790897/CookiesClerk#1]
插件很实用也很好用，就是ui界面不太美观，比如图标，界面里面的图标，都不太美观。希望可以换一个更漂亮的ui。作者大大加油！

**Comment by 14790897** [comment]
非常感谢您的宝贵反馈！我很高兴听到您觉得这个插件实用和好用。

关于UI和图标的问题，我非常感谢您的诚实意见。我明白视觉体验对于用户来说是非常重要的，所以我已经把这个问题加入到了未来更新的计划中。

再次感谢您的支持和建议，敬请期待我们的下一个版本！

**Comment by 14790897** [comment]
好的,我会针对这些问题进行改进

**Comment by 14790897** [comment]
第一个问题：现在第二个图标按钮可以使用选择账户的cookie打开对应网页
第二个问题，我无法判断是否是空账户，我选择了另一个办法：在浏览器打开时自动清除已关闭页面且无别名的账户
第三个问题，现在已经减少大部分弹窗
ui还没有好的想法，图标是ai画的，我不会画图，以后再说

**Comment by TheKonka** [comment]
> 实际上，插件商店有一些类似功能的产品，比如multilogin（功能较为简单），sessionbox（可能需要付费），由于它们的限制，所以我打算做这个插件看能不能填补这个空白

大佬，你这插件的原理跟他们的不一样，第一次知道还能这样做，但是我看源码还是有些看不明白，可以再简单介绍下原理吗？

**Comment by 14790897** [comment]
我在新的issue里回答你 #4

> > 实际上，插件商店有一些类似功能的产品，比如multilogin（功能较为简单），sessionbox（可能需要付费），由于它们的限制，所以我打算做这个插件看能不能填补这个空白
> 
> 大佬，你这插件的原理跟他们的不一样，第一次知道还能这样做，但是我看源码还是有些看不明白，可以再简单介绍下原理吗？

**Comment by P3R5T7U9** [comment]
> > > 第一个问题：现在第二个图标按钮可以使用选择账户的cookie打开对应网页 第二个问题，我无法判断是否是空账户，我选择了另一个办法：在浏览器打开时自动清除已关闭页面且无别名的账户 第三个问题，现在已经减少大部分弹窗 ui还没有好的想法，图标是ai画的，我不会画图，以后再说
> > 
> > 
> > 感谢，我今晚试试看。
> 
> 过段时间，我会在B站做一个视频，来宣传一下这个好用的插件。这个多账户功能以前是某些浏览器的特色功能。现在可以通过拓展实现，可以的🙏

时隔五个多月，挖下；

那不知老哥你之后在B站上有无发宣传视频来介绍“CookiesClerk”这个可管理同一网站多个cookies的浏览器扩展？？

之前在B站上搜了下，没翻到相关介绍视频，也可能是我搜索关键词⑧对，如果老哥你之前已在B站上发过宣传视频的话，麻烦老哥你甩个视频BV号指个路呗

**Comment by 14790897** [comment]
> > > > 第一个问题：现在第二个图标按钮可以使用选择账户的cookie打开对应网页 第二个问题，我无法判断是否是空账户，我选择了另一个办法：在浏览器打开时自动清除已关闭页面且无别名的账户 第三个问题，现在已经减少大部分弹窗 ui还没有好的想法，图标是ai画的，我不会画图，以后再说
> > > 
> > > 
> > > 感谢，我今晚试试看。
> > 
> > 
> > 过段时间，我会在B站做一个视频，来宣传一下这个好用的插件。这个多账户功能以前是某些浏览器的特色功能。现在可以通过拓展实现，可以的🙏
> 
> 时隔五个多月，挖下；
> 
> 那不知老哥你之后在B站上有无发宣传视频来介绍“CookiesClerk”这个可管理同一网站多个cookies的浏览器扩展？？
> 
> 之前在B站上搜了下，没翻到相关介绍视频，也可能是我搜索关键词⑧对，如果老哥你之前已在B站上发过宣传视频的话，麻烦老哥你甩个视频BV号指个路呗 (小声：发此条comment目的是想为老哥你发的宣传视频投币&点赞，也为这个浏览器扩展的宣传贡献一份微薄力量😖)

https://www.bilibili.com/video/BV1gH4y1D7MN/
https://www.youtube.com/watch?v=yfKICnGQ2n0
感谢🙏

**Comment by 14790897** [comment]
> > > > > 第一个问题：现在第二个图标按钮可以使用选择账户的cookie打开对应网页 第二个问题，我无法判断是否是空账户，我选择了另一个办法：在浏览器打开时自动清除已关闭页面且无别名的账户 第三个问题，现在已经减少大部分弹窗 ui还没有好的想法，图标是ai画的，我不会画图，以后再说
> > > > 
> > > > 
> > > > 感谢，我今晚试试看。
> > > 
> > > 
> > > 过段时间，我会在B站做一个视频，来宣传一下这个好用的插件。这个多账户功能以前是某些浏览器的特色功能。现在可以通过拓展实现，可以的🙏
> > 
> > 
> > 时隔五个多月，挖下；
> > 那不知老哥你之后在B站上有无发宣传视频来介绍“CookiesClerk”这个可管理同一网站多个cookies的浏览器扩展？？
> > 之前在B站上搜了下，没翻到相关介绍视频，也可能是我搜索关键词⑧对，如果老哥你之前已在B站上发过宣传视频的话，麻烦老哥你甩个视频BV号指个路呗 (小声：发此条comment目的是想为老哥你发的宣传视频投币&点赞，也为这个浏览器扩展的宣传贡献一份微薄力量😖)
> 
> 您好，十分抱歉。由于这几个月备考，没有落实。我会近期出一个视频，到时候再回复😅

感谢🙏，理解，没关系
